name: Cron Send Reminder

# Jadwal eksekusi
on:
  schedule:
    - cron: "30 6 * * *"  # Jam 13:30 WIB (06:30 UTC)
  workflow_dispatch:      # Bisa juga dijalankan manual lewat GitHub

jobs:
  call-cron-url:
    runs-on: ubuntu-latest

    steps:
      - name: Call reminder URL
        run: |
          curl -L --max-time 30 https://account-kerja.great-site.net/cron/send_reminder
